src/AppBundle/Form/UserType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UserType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('enabled')
            ->add('email', 'email', array('label' => 'form.email', 'translation_domain' => 'FOSUserBundle'))
            ->add('username', null, array('label' => 'form.username', 'translation_domain' => 'FOSUserBundle'))
            ->add('plainPassword', 'repeated', array(
                'type' => 'password',
                'options' => array('translation_domain' => 'FOSUserBundle'),
                'first_options' => array('label' => 'form.password'),
                'second_options' => array('label' => 'form.password_confirmation'),
                'invalid_message' => 'fos_user.password.mismatch',
            ))
            ->add('project')
             ->add('roles', 'collection', array(
                   'type' => 'choice',
                   'options' => array(
                       'label' => false, /* Ajoutez cette ligne */
                       'choices' => array(
                           'ROLE_ADMIN' => 'Admin',
                           'ROLE_USER' => 'User'
                       )
                   )
               )
           )
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\User'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'appbundle_user';
    }
}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use AppBundle\Entity\Setting;
use AppBundle\Entity\IssueType;
use AppBundle\Entity\IssueStatus;
use AppBundle\Entity\Priority;


class DefaultController extends Controller
{
	public function indexAction() {
		$em = $this->getDoctrine()->getManager();
		
		 return $this->render('AppBundle:Default:index.html.twig', array());
	}

	public function settingsAction() {
		$em = $this->getDoctrine()->getManager();
		 return $this->render('AppBundle:Default:index.html.twig', array());

	}

}

src/AppBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Dashboard</h1>


{% endblock %}

src/AppBundle/Resources/views/Default/main_menu.html.twig
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			<span class="sr-only">{{_settings.app.name}}</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{{path('app_homepage')}}">{{_settings.app.name}}</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				{% if app.user %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projects <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							{% if app.user.project is defined %}
								{% for project in app.user.project %}
									<li><a href="{{path('project_show', {'id':project.id})}}">{{project.name}}</a></li>
								{% endfor %}
							{% endif %}
								<li class="divider"></li>
								<li><a href="{{path('project_new')}}">{{"New project"|trans}}</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Boards <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							{% if app.user.board is defined %}
								{% for board in app.user.board %}
									<li><a href="{{path('board_show', {'id':board.id})}}">{{board.name}}</a></li>
								{% endfor %}
							{% endif %}
							<li class="divider"></li>
							<li><a href="{{path('board_new')}}">{{"New board"|trans}}</a></li>
						</ul>
					</li>
					{% if app.user.project is defined %}
						<li>
							<a class="btn btn-primary create_issue" href="{{path('issue_new')}}" {{ app.user.project|length>0?'':'disabled'}} ><i class="fa fa-plus"></i> {{"Issue"|trans}}</a>
						</li>
					{% endif %}
				{% endif %}
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if app.user %}
					{% if is_granted('ROLE_ADMIN') %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-cog"></i> <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{path('project')}}">{{"Projects"|trans}}</a></li>
								<li><a href="{{path('board')}}">{{"Boards"|trans}}</a></li>
								<li><a href="{{path('user')}}">{{"Users"|trans}}</a></li>
								<li class="divider"></li>
								<li><a href="{{path('app_settings')}}">{{"Settings"|trans}}</a></li>
							</ul>
						</li>
					{% endif %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Me <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="{{path('fos_user_profile_edit')}}">{{"Profile"|trans}}</a></li>
							<li><a href="{{path('fos_user_security_logout')}}">{{"Logout"|trans}}</a></li>
						</ul>
					</li>
				{% else %}
					<li><a href="{{path('fos_user_security_login')}}">{{"Login"|trans}}</a></li>
				{% endif %}
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>

src/AppBundle/Resources/views/Default/modal.html.twig
 <div class="modal fade" id="issueModal" tabindex="-1" role="dialog" aria-labelledby="issueModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="issueModalLabel">Issue</h4>
      </div>
      <div class="modal-body">
           
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>